### ISSUE TITLE
Error : While setting up Tezster --  .action(async function(){

### ISSUE THREAD

**Issue by MajumderDibyo** [Tezsure/Tezster#21]
while using command :
    

> sudo tezster setup

    sudo tezster setup
    [sudo] password for aditya: 
    /usr/local/lib/node_modules/tezster/tezster.js:108
    .action(async function(){
            ^^^^^
    SyntaxError: missing ) after argument list
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.runMain (module.js:604:10)
        at run (bootstrap_node.js:383:7)
        at startup (bootstrap_node.js:149:9) 

Encountered the error, How can these be resolved

**Comment by MajumderDibyo** [comment]
This happened due to the older version of nodeJs that does not support async function. Update the node version 
`npm install npm@latest -g`
And  `sudo tezster setup` will work fine

**Comment by yoyodefi** [comment]
Great. Resolved.
